// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/add/food": {
            "post": {
                "description": "Add food to the menu, food name must be unique",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "sunbula"
                ],
                "summary": "Add food",
                "parameters": [
                    {
                        "description": "Food info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.PreEnterFood"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/delete/food/": {
            "delete": {
                "description": "deletes food by its name",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "sunbula"
                ],
                "summary": "Delete food",
                "parameters": [
                    {
                        "type": "string",
                        "description": "delete food by name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/food/": {
            "get": {
                "description": "it gets all information about the asked food",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "sunbula"
                ],
                "summary": "Get food",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search food by name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Food"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/menu": {
            "get": {
                "description": "shows all items in the menu",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sunbula"
                ],
                "summary": "Menu",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/types.Food"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/menu/dessert": {
            "get": {
                "description": "it gets dessert information",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "dessert",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Food"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/menu/drink": {
            "get": {
                "description": "it gets drink information",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "drink",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Food"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/menu/first-meal": {
            "get": {
                "description": "it gets first meal information",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "first meals",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Food"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/menu/salad": {
            "get": {
                "description": "it gets salad information",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "salads",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Food"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/menu/second-meal": {
            "get": {
                "description": "it gets second meal information",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "second meals",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Food"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/table": {
            "post": {
                "description": "you can choose one of the free tables",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tables"
                ],
                "summary": "Order a table",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "table number",
                        "name": "num",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/table/buy": {
            "post": {
                "description": "you can buy any food",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tables"
                ],
                "summary": "Buy a product",
                "parameters": [
                    {
                        "description": "order info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/postgres.PurchaseR"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Purchase"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/tables": {
            "get": {
                "description": "shows all the free tables",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tables"
                ],
                "summary": "GetTables",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/update/food/": {
            "put": {
                "description": "Update food in the menu",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "sunbula"
                ],
                "summary": "Update food",
                "parameters": [
                    {
                        "type": "string",
                        "description": "update food by name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Food info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UpdateFood"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "postgres.PurchaseR": {
            "type": "object",
            "properties": {
                "beverage_id": {
                    "type": "string"
                },
                "dessert_id": {
                    "type": "string"
                },
                "first_meal_id": {
                    "type": "string"
                },
                "salad_id": {
                    "type": "string"
                },
                "second_meal_id": {
                    "type": "string"
                },
                "table_id": {
                    "type": "string"
                }
            }
        },
        "types.Food": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "cooked_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ingredients": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "types.PreEnterFood": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "ingredients": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "types.Purchase": {
            "type": "object",
            "properties": {
                "beverage_id": {
                    "type": "string"
                },
                "dessert_id": {
                    "type": "string"
                },
                "first_meal_id": {
                    "type": "string"
                },
                "purchased_at": {
                    "type": "string"
                },
                "salad_id": {
                    "type": "string"
                },
                "second_meal_id": {
                    "type": "string"
                },
                "table_id": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "types.UpdateFood": {
            "type": "object",
            "properties": {
                "ingredients": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Swagger Restaurant API",
	Description:      "This is a restaurant project.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
